# Set global configuration arguments
cask_args appdir: "/Applications"

# Taps
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "acrogenesis/macchanger"
tap "snyk/tap"
tap "seek-jobs/tools"

# Cask dependencies
brew "mas"
cask "xquartz"

# Shells
# Note: Don't forget to add shells to `/etc/shells` before running `chsh`.
brew "bash"
brew "zsh"
brew "zsh-completions"
brew "antigen"

# CLI utilities
# Note: This replaces some (outdated) built-in macOS utilities with the GNU equivalents
# Don't forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew "coreutils"
brew "curl-openssl"
#brew "findutils" # Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
brew "git"
brew "git-lfs"
brew "gh"
brew "grep"
brew "gnu-sed" # Install GNU `sed`, overwriting the built-in `sed`
brew "moreutils" # Install more useful GNU utilities like `sponge`
brew "openssh"
brew "rsync"
brew "screen"
brew "ssh-copy-id", link: true
brew "tmux"
brew "tree"
brew "wget"
brew "ack"
brew "findutils"
brew "gnu-tar"
cask "session-manager-plugin"
brew "glide"
brew "cowsay"
brew "figlet"
brew "fortune"
brew "lolcat"
brew "starship"
brew "telnet"
brew "tldr"
brew "watch"

# infra as code / cloud / db tools
brew "awscli"
brew "awslogs"
brew "aws-es-proxy"
brew "mydumper"
brew "mysql-client"
brew "terraform"
brew "haproxy"
brew "dnsmasq", restart_service: true

# dev productivity
brew "direnv"
brew "gomplate"

# critical utils
cask "1password"
cask "1password-cli"


# seek only tools
brew "seek_auth"
brew "seek_bastion"
brew "seek_gantry"
brew "snyk"

# Other useful tools
brew "highlight" # https://developer.atlassian.com/blog/2015/08/beautiful-presentations-with-highlight/
brew "multimarkdown"
brew "reattach-to-user-namespace" # https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard

# # Image tools
# brew "ffmpeg", args: ["with-libvpx", "with-webp", "with-x265"]
# brew "graphicsmagick"
# brew "imagemagick", args: ["with-librsvg", "with-webp"]

# Compression tools
brew "bzip2"
brew "gzip"

# Mac OS tools
brew "duti" # Required for setting preferences (https://github.com/moretension/duti/)
brew "imagesnap"
brew "mackup"
brew "tccutil" # Required for setting preferences
brew "trash"
brew "wifi-password"

# Programming languages
# Installing Python/Ruby with Homebrew is unnecessary,
# as they will be installed and managed via pyenv/rbenv respectively
brew "go"
brew "python"
brew "ruby-build"
brew "rbenv" # Ruby
brew "nvm"
brew "yarn" # Faster than npm
brew "jq"
brew "yq"

# Network tools
brew "namebench"
brew "nmap"
brew "speedtest_cli"

# Security tools
# brew "foremost"
# brew "justwatchcom/gopass/gopass"
# brew "hashpump"
brew "sqlmap"

# Install GUI applications
cask "dropbox"
cask "iterm2"
cask "vlc"
cask "iina"
cask "wkhtmltopdf"
cask "alfred"
cask "charles"
cask "disk-inventory-x"
cask "dropbox"
cask "iterm2"
cask "postman"
cask "sublime-text"
cask "evernote"
cask "gpg-suite"
cask "gotomeeting"
cask "jd-gui"
cask "obs"
cask "textexpander"
cask "tunnelblick"
cask "unetbootin"
cask "visual-studio-code"
cask "wireshark"
cask "whatsapp"
cask "graphiql"
cask "ngrok"
cask "burn"

# Browsers
cask "google-chrome"
cask "firefox"
cask "microsoft-edge"

# Virtulization applications
# cask "vmware-fusion"
# cask "vagrant"
# cask "vagrant-manager"

# Preference Panes
# cask "hosts"

# Screensavers
# cask "ios-saver"

# Drivers
cask "fujitsu-scansnap-manager-ix500"
cask "synologyassistant"

# Services
cask "markdown-service-tools"

# QuickLook plugins
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlstephen"
cask "webpquicklook"
cask "quicklook-json"
cask "qlprettypatch"
cask "quicklook-csv"
cask "qlimagesize"
cask "betterzip"

# Color Picker plugins
cask "colorpicker-skalacolor"

# Fonts
cask "font-anonymous-pro"
cask "font-bebas-neue"
cask "font-comic-neue"
cask "font-dejavu-sans-mono-nerd-font"
cask "font-league-gothic"
cask "font-liberation"
cask "font-liberation-nerd-font"
cask "font-anonymous-pro"
cask "font-droid-sans-mono-nerd-font"
cask "font-nixie-one"
cask "font-office-code-pro"
cask "font-pt-mono"
cask "font-source-sans-pro"
cask "font-meslo-for-powerline"
cask "font-meslo-lg-dz"
cask "font-meslo-lg"
cask "font-inconsolata-dz-for-powerline"
cask "font-inconsolata-for-powerline-bold"
cask "font-inconsolata-for-powerline"
cask "font-inconsolata-g"
cask "font-inconsolata-go-nerd-font"
cask "font-inconsolata-lgc-nerd-font"
cask "font-inconsolata-nerd-font"


# MAS applications
mas "Guidance", id: 412759995
mas "Amphetamine", id: 937984704
mas "Compressor", id: 424390742
mas "Disk Cartography", id: 905264208
mas "DxO OpticsPro for Photos", id: 1056077392
mas "Edison Mail", id: 1489591003
mas "Fantastical", id: 975937182
mas "Final Cut Pro", id: 424389933
mas "Gifski", id: 1351639930
mas "GIPHY CAPTURE", id: 668208984
mas "iMovie", id: 408981434
mas "Jira", id: 1475897096
mas "Magnet", id: 441258766
mas "Marked 2", id: 890031187
mas "Microsoft Excel", id: 462058435
mas "Microsoft OneNote", id: 784801555
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Remote Desktop", id: 715768417
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft To Do", id: 1274495053
mas "Microsoft Word", id: 462054704
mas "Motion", id: 434290957
mas "OneDrive", id: 823766827
mas "Pixelmator", id: 407963104
mas "Slack", id: 803453959
mas "Telegram", id: 747648890
mas "Trello", id: 1278508951
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835

# Apple MAS applications
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
