export TERM="xterm-256color"
source $(brew --prefix)/share/antigen/antigen.zsh

antigen use oh-my-zsh

setup_plugins() {
    antigen bundle git
    antigen bundle git-flow
    antigen bundle aws
    antigen bundle marked2
    antigen bundle mgryszko/jvm
    antigen bundle psprint/zsh-navigation-tools
    antigen bundle command-not-found
    antigen bundle zsh-users/zsh-syntax-highlighting
    antigen bundle osx
    antigen bundle Tarrasch/zsh-colors
    antigen bundle KyleChamberlin/zsh_maven_plugin
    antigen bundle brew
    antigen bundle docker
    antigen bundle go
    antigen bundle gradle
    antigen bundle heroku
    antigen bundle lein
    antigen bundle mvn
    antigen bundle postgres
    antigen bundle sbt
    antigen bundle scala
    antigen bundle node
    antigen bundle npm
    antigen bundle nvm
    antigen bundle gem
    antigen bundle bundler
    antigen bundle rbenv
    antigen bundle gem
    antigen bundle bundler
    antigen bundle pip
    antigen bundle python
    antigen bundle brew
    antigen bundle brew cask
}

setup_theme() {
    DEFAULT_USER=$USER
    POWERLEVEL9K_PROMPT_ON_NEWLINE=true
    POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=true
    POWERLEVEL9K_NODE_VERSION_FOREGROUND='black'
    POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S}"
    POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time context dir vcs)
    POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status rbenv background_jobs)
    POWERLEVEL9K_STATUS_VERBOSE=true
    POWERLEVEL9K_SHOW_CHANGESET=true
    POWERLEVEL9K_CHANGESET_HASH_LENGTH=7

    POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
    POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
    POWERLEVEL9K_INSTALLATION_PATH=$ANTIGEN_BUNDLES/bhilburn/powerlevel9k

    antigen theme bhilburn/powerlevel9k powerlevel9k
}

setup_plugins && setup_theme && antigen apply

export PATH=/usr/local/bin:$PATH
export MAVEN_OPTS="-Xmx2048m -XX:+CMSClassUnloadingEnabled -XX:+UseCompressedOops"
export LEARNDOT_CONFIG="/Users/faizhasim/dev/stash/unicorn-scala/config/development.yml"
export JAVA_HOME=$(/usr/libexec/java_home)

export NVM_DIR="/Users/faizhasim/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# added by travis gem
[ -f /Users/faizhasim/.travis/travis.sh ] && source /Users/faizhasim/.travis/travis.sh

# Hyperterm Compatability (see https://github.com/zeit/hyperterm/issues/360)
export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export PATH="/usr/local/sbin:/usr/local/mysql/bin:$HOME/.yarn/bin:$PATH"
